export const DOWNLOADING = "DOWNLOADING";
export const DOWNLOADING_SUCCESS = "DOWNLOADING_SUCCESS";
export const DOWNLOADING_ERROR = "DOWNLOADING_ERROR";

export const DOWNLOADING_ITEM = "DOWNLOADING_ITEM";
export const DOWNLOADING_ITEM_SUCCESS = "DOWNLOADING_ITEM_SUCCESS";
export const DOWNLOADING_ITEM_ERROR = "DOWNLOADING_ITEM_ERROR";

export const ITEM_FAV_ADD = "ITEM_FAV_ADD";
export const ITEM_FAV_REMOVE = "ITEM_FAV_REMOVE";

export const APPLY_FILTER = "APPLY_FILTER";
export const CLEAR_FILTER = "CLEAR_FILTER";

export const CLEAR_DATA = "CLEAR_DATA";
